apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
   name: transport-server-tls
   labels:
     f5cr: "true"
spec:
   virtualServerAddress: "10.1.10.22"
   virtualServerPort: 443
   mode: standard
   snat: auto
   pool:
     service: my-crd
     servicePort: 443
     monitor:
       type: tcp
       interval: 10
       timeout: 10

