apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: my-new-virtual-server
  labels:
    f5cr: "true"
    namespace: default
spec:
  host: cafe.example.com
  virtualServerAddress: "172.16.3.4"
  waf: /Common/linux-low
  httpTraffic: redirect
  tlsProfileName: edge-tls
  httpTraffic: redirect
  pools:
  - path: /coffee
    service: svc-1
    servicePort: 80
    monitor:
        interval: 20
        recv: ""
        send: /
        timeout: 10
        type: https
