kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-override
  namespace: default
  labels:
    f5type: virtual-server
    overrideAS3: "true"
data:
  template: |
    {
        "declaration": {
            "ocpnodeport": {
                "Shared": {
                    "ocp_http_vs": {
                        "securityLogProfiles": [
                            {
                                "bigip": "/Common/Log all requests"
                            }
                        ],
                        "policyWAF": {
                            "bigip": "/Common/linux-low"
                        },
                        "persistenceMethods": [],
                        "profileMultiplex": {
                            "bigip": "/Common/oneconnect"
                        },
                        "profileHTTP":{"use": "XFF_HTTP_Profile"},
                        "policyIAM": {
                          "bigip": "/Common/openshift-oauth-sso-ap"
                        }
                    },
                    "XFF_HTTP_Profile": {
                        "class": "HTTP_Profile",
                        "xForwardedFor": true
                    }
                }
            }
        }
    }
