kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-override
  namespace: default
  labels:
    f5type: virtual-server
    overrideAS3: "true"
data:
  template: |
    {
        "declaration": {
            "ocpnodeport": {
                "Shared": {
                    "ocp_https_vs": {
                        "policyIAM": {
                          "bigip": "/Common/openshift-oauth-sso-ap"
                                     }
                      }
                   }
                }
            }
     }

